### ISSUE TITLE
Add README.md w/ Travis Badge

### ISSUE THREAD

**Issue by miroswan** [pottery123/rover#1]
A README.md file is a markdown file that gives users and developers the information they need to get started with your project. The Travis badge provides immediate feedback to users of builds are passing or failing. 
- Try adding a README.md
- Try adding a Travis badge that references the master branch within your README.md file

References:
- [Markdown Docs](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/)
- [Badge Docs](https://docs.travis-ci.com/user/status-images/)

**Comment by pottery123** [comment]
https://github.com/pottery123/rover/pull/2
